figure
subplot(2,2,1)
title([Rivers(cf).Name ' - reaches'])
plot(Rivers(cf).Reaches.x/1000,Rivers(cf).Reaches.Q)
xlabel('Flow distance in km')
ylabel('Reach averaged discharge in m^3/s')
subplot(2,2,2)
plot(Rivers(cf).Reaches.x/1000,Rivers(cf).Reaches.H)
xlabel('Flow distance in km')
ylabel('Reach averaged elevations (m)')
subplot(2,2,3)
plot(Rivers(cf).Reaches.x/1000,Rivers(cf).Reaches.W)
xlabel('Flow distance in km')
ylabel('Reach averaged widths (m)')
subplot(2,2,4)
plot(Rivers(cf).Reaches.x/1000,Rivers(cf).Reaches.S*100000)
xlabel('Flow distance in km')
ylabel('Reach averaged slopes (cm/km)')
subplot(2,2,1)
title([Rivers(cf).Name ' - reaches'])