        figure
        subplot(2,2,1)
        plot(Rivers(cf).Nodes.X/1000,Rivers(cf).Nodes.Q,'.')
        xlabel('Flow distance in km')
        ylabel('Discharge in m^3/s')
        subplot(2,2,2)
        plot(Rivers(cf).Nodes.X/1000,Rivers(cf).Nodes.H,'.')
        xlabel('Flow distance in km')
        ylabel('Elevations (m)')
        subplot(2,2,3)
        plot(Rivers(cf).Nodes.X/1000,Rivers(cf).Nodes.W,'.')
        xlabel('Flow distance in km')
        ylabel('Widths (m)')
        subplot(2,2,1)
        title([Rivers(cf).Name ' - nodes'])